### ISSUE TITLE
Melodic release and system setup?

### ISSUE THREAD

**Issue by Dkaka** [fada-catec/leica_gazebo_simulation#1]
Hi there,  would it be possible to have a melodic release? Also, could you please share your system setup to run the package? I've followed the instructions on the ros wiki page and github readme ,everything looks fine except (no obvious warning) I couldn't receive any output on c5/simulator/scan and c5/simulator/cloud. I tried the following setup:
1. ROS Kinect  with compiled version of pcl and vtk  (github instruciton) 
2. ROS Melodic with dependencies from ubuntu packages, with/ without Nvidia GPU. (I could see the blue scan line in gazebo with dGPU )

**Comment by imlaras** [comment]
Hi! Thank you for using our package! Yes, we are planning a Melodic release soon. 

Sorry for the problems you have encountered. We are currently working on the latest release of the package, I hope these updates can solve your problem. Please, try new usage instructions described on readme. 

Just for checking, have you pressed play on Gazebo? Default launch is paused.

**Comment by Dkaka** [comment]
Really appreciate for getting back to me! Thanks for making the update.
now I could get pcd file out. 

And yes I did previously clicked on play in the gazebo, took a few attempts to realize the `paused` parameter in the launch file.

However, I did come across situations where the package isn't working as expected, one is with the following: 
on `roslaunch leica_gazebo_simulation c5_init.launch namespace:=c5`

`[pcl::PCDWriter::writeASCII] Input point cloud has no data!`
and no pcd file is produced. Although this doesn't happen all the time.

and another issue is that I'm having trouble visualising the `/c5/simulator/cloud` message in rviz as there is missing `frame_id` in the message header. perhaps tf related issue?

Should I open new issues for these?

**Comment by imlaras** [comment]
Hi Dkaka, sorry for my late reply

I think both problems you experienced were related. Due to a wrong pointer initialisation of the one containing the point cloud, sometimes the data was lost and it was unable to generate the pcd. 

This also meant that the point cloud information was incomplete and did not include the `frame_id`. 
 
For rviz, you should change the `global options/fixed frame` from _map_, which is the default to _world_, which is the one that has been set in this project. 

I hope the changes added in #2 will solve your problem.

**Comment by Dkaka** [comment]
Hi imlaras, sorry for such late reply. Now it works like a charm!  Appreciate for putting time into fixing this!
